# Source: k8s-datadog-operator/templates/datadogagent.yaml
apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  labels:
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "datadogagent"
    helm.sh/chart: "k8s-datadog-operator-1.5.0"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/resource-policy": keep
spec:
  global:
    clusterName: sandbox
    credentials:
      apiSecret:
        secretName: env-secrets
        keyName: dd_api_key
      appSecret:
        secretName: env-secrets
        keyName: dd_app_key
    podLabelsAsTags:
      app: service
      "release": helm_release
      deploy_infra: type
      deploy_env: env
      "stack": stack
      environment: environment
      namespace: namespace
      owner: owner
      region: region
      log_type: log_type
      service_language: service_language
    nodeLabelsAsTags:
      "node_type": managed_node
      "eks.amazonaws.com/compute-type": compute-type
  # Enable Features
  features:
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
    dogstatsd:
      hostPortConfig:
        enabled:  true
    logCollection:
      enabled:  true
      containerCollectAll:  true
    # Enabled Process Monitoring.
    liveProcessCollection:
      enabled:  true
    # Enabled Network Performance Monitoring.
    npm:
      enabled:  false
    # Enables OOMKill eBPF-based check.
    oomKill:
      enabled:  true
    # Enabled Universal Service Monitoring.
    usm:
      enabled:  true

  override:
    # Node Agent Configuration
    nodeAgent:
      env:
        - name: DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION
          value: "true"
      extraConfd:
        configDataMap:
          linkerd.yaml: |-
            ad_identifiers:
              - proxy
            init_config:
            instances:
              - openmetrics_endpoint: "http://%%host%%:4191/metrics"
        
          tcp_check.yaml: |-
            init_config:
            instances:
              - name: trace-agent
                host: localhost
                port: 8126

      # Specify additional environment variables in the container. See https://docs.datadoghq.com/agent/kubernetes/?tab=helm#environment-variables. Configurations specific to the containers "agent" and "trace-agent"
      containers: 
        trace-agent:
          env:
            - name: DD_APM_IGNORE_RESOURCES
              value: "GET /auth/health/ready, GET /actuator/health, GET /health, GET /ready, GET /live, GET /metrics, GET /api/healthcheck, GET /api/health, GET /q/health, GET /healthcheck, EntryPoint traefik, EntryPoint websecure AWSALB"
    # Cluster Agent Configuration
    clusterAgent:
      replicas: 2
      containers:
        cluster-agent:
          env:
            - name: DD_CLUSTER_AGENT_COLLECT_KUBERNETES_TAGS
              value: "true"

