apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/resource-policy": keep
spec:
  global:
    clusterName: "somename"
    credentials:
      apiSecret:
        secretName: env-secrets
        keyName: dd_api_key
      appSecret:
        secretName: env-secrets
        keyName: dd_app_key
    podLabelsAsTags:
      app: service
      "release": helm_release
      deploy_infra: type
      deploy_env: env
      "stack": stack
      environment: environment
      namespace: namespace
      owner: owner
      region: region
      log_type: log_type
      service_language: service_language
    nodeLabelsAsTags:
      "node_type": managed_node
      "eks.amazonaws.com/compute-type": compute-type
  # Enable Features
  features:
    apm:
      enabled: 'false'
      hostPortConfig:
        enabled: 'false'
    dogstatsd:
      hostPortConfig:
        enabled: 'false'
    logCollection:
      enabled: 'false'
      containerCollectAll: 'false'
    liveProcessCollection:
      enabled: 'false'
    npm:
      enabled: 'false'
    usm:
      enabled: 'false'
      
  override:
    # Node Agent configuration
    nodeAgent:
      env:
        - name: DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION
          value: 'true'
      extraConfd:
        configDataMap:
          linkerd.yaml: |-
            ad_identifiers:
              - proxy
            init_config:
            instances:
              - openmetrics_endpoint: "http://%%host%%:4191/metrics"
        
          tcp_check.yaml: |-
            init_config:
            instances:
              - name: trace-agent
                host: localhost
                port: 8126
                
      # Configurations specific to the containers "agent" and "trace-agent"
      containers: 
        trace-agent:
          env:
            - name: DD_APM_IGNORE_RESOURCES
              value: "GET /auth/health/ready, GET /actuator/health, GET /health, GET /ready, GET /live, GET /metrics, GET /api/healthcheck, GET /api/health, GET /q/health, GET /healthcheck, EntryPoint traefik, EntryPoint websecure AWSALB"
    # Cluster Agent configuration
    clusterAgent:
      replicas: 1
      containers:
        cluster-agent:
          env:
            - name: DD_CLUSTER_AGENT_COLLECT_KUBERNETES_TAGS
              value: "true"
